apiVersion: v1
kind: Service
metadata:
  name: kargo-podinfo
spec:
  ports:
  - nodePort: 32090
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: kargo-podinfo
  type: NodePort
